### ISSUE TITLE
Investigating IMAP/POP3 Connection Issues

### ISSUE THREAD

**Issue by titanism** [forwardemail/status.forwardemail.net#1165]
We are currently investigating intermittent connection issues to IMAP/POP3 servers..

**Comment by graemev** [comment]
Yep, I'd noticed that my overnight tests were failing. Before reporting I checked the status, it showed all sites as green . Then I modified my overnight test. It was originally setup just to check that my system could send and receive email (e.g. not no internet connection or DNS etc) so it has calls to you, to gmail etc.  I've now factored out the single call to pop on forwardemail because I noted it took more than5 minutes to check 1 mailbox that held 3 emails..... this caused a clash with the subsequent poll.

**Comment by vincentmaule** [comment]
~~Is it known for how this has been happening for?~~
Been facing issues for I think 15 hours.

I can see from the other issue how long it's been happening, thanks for keep us updated :)
